apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplicationcontroller
spec:
  replicas: 3
  selector:
    app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
      name: nginx-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
