apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    service-type: nodeportservice
spec:
  type: NodePort
  selector:
       app: nginx-app
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 80
