apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    mydeployment: mydeploymentlabel
spec:
  replicas: 3
  selector:
    matchLabels:
       app: nginx-app
    matchExpressions:
      - {key: tier, operator: In, values: [front-end, web-app]}
  template:
    metadata:
      labels:
        app: nginx-app
        tier: front-end
        tier: web-app
      name: nginx-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.16.1
        ports:
        - containerPort: 80
