apiVersion: v1
kind: Pod
metadata:
   name: myhostpathdir
spec:
 containers:
# - image: nginx
 - image: redis
   name: redis-container
   volumeMounts:
   - name: myhostpathvolume
     mountPath: /test-mnt
 volumes:
 - name: myhostpathvolume
   hostPath:
     path: /test-vol
