apiVersion: v1
kind: Pod
metadata:
   name: myemptdir
spec:
 containers:
# - image: nginx
 - image: k8s.gcr.io/test-webserver
   name: test-container
   volumeMounts:
   - name: myemptydirvolume
     mountPath: /cache
 volumes:
 - name: myemptydirvolume
   emptyDir: {}
